#!/usr/bin/env python3
"""
amalgamate.py - emit a single-header build of the receiver.

Writes earshot_single.h to the repo root: the public API always, plus the
implementation guarded by EARSHOT_IMPLEMENTATION (define it in exactly one
translation unit, stb-style).

    #define EARSHOT_IMPLEMENTATION
    #include "earshot_single.h"

SPDX-License-Identifier: Apache-2.0
"""
import os
import re

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
PUBLIC = "include/earshot.h"
IMPL = [
    "src/earshot_internal.h",
    "src/crc.c",
    "src/siphash.c",
    "src/fountain.c",
    "src/envelope.c",
    "src/earshot.c",
]

_LOCAL_INCLUDE = re.compile(r'^[ \t]*#[ \t]*include[ \t]+"[^"]+".*$', re.M)


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as fh:
        return fh.read()


def strip_local_includes(text):
    return _LOCAL_INCLUDE.sub("", text)


def main():
    parts = [
        "/* earshot_single.h - generated by tools/amalgamate.py; do not edit.",
        " *",
        " * Public API always. Define EARSHOT_IMPLEMENTATION in one translation",
        " * unit to pull in the implementation.",
        " *",
        " * SPDX-License-Identifier: Apache-2.0",
        " */",
        "#ifndef EARSHOT_SINGLE_H",
        "#define EARSHOT_SINGLE_H",
        "",
        strip_local_includes(read(PUBLIC)),
        "#endif /* EARSHOT_SINGLE_H */",
        "",
        "#ifdef EARSHOT_IMPLEMENTATION",
    ]
    for rel in IMPL:
        parts.append("/* ================= %s ================= */" % rel)
        parts.append(strip_local_includes(read(rel)))
    parts.append("#endif /* EARSHOT_IMPLEMENTATION */")

    dst = os.path.join(ROOT, "earshot_single.h")
    with open(dst, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts) + "\n")
    print("wrote", os.path.relpath(dst, ROOT))


if __name__ == "__main__":
    main()
