#!/usr/bin/env python3
"""
soliton_table.py - generate src/tx/soliton_table.h (spec/PROFILE-A.md section 5).

The device-side encoder must not use floating point, but it has to pick the same
fountain degree as the phone-side decoder, which computes the robust-soliton CDF
in double. This emits a fixed-point table

    cdf_int[K][m] = round(cdf_float(K)[m] * 2**32)      (clamped to 2**32 - 1)

and verifies exhaustively that every one of the 65536 possible 16-bit seeds
produces an identical coded block set with the integer path as with the float
reference, for every K in range.

  python3 soliton_table.py                 # K = 1..32, write the header
  python3 soliton_table.py --kmax 12       # smaller table
  python3 soliton_table.py --check-only

SPDX-License-Identifier: Apache-2.0
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import earshot_tx as tx  # noqa: E402

TWO32 = 1 << 32
OUT = os.path.normpath(os.path.join(os.path.dirname(__file__),
                                    "..", "src", "tx", "soliton_table.h"))


def cdf_int(K):
    c = tx.soliton_cdf(K)
    row = [0] * (K + 1)
    for m in range(1, K + 1):
        row[m] = min(TWO32 - 1, int(round(c[m] * TWO32)))
    row[K] = TWO32 - 1
    return row


def int_degree(row, K, draw):
    lo, hi = 1, K
    while lo < hi:
        m = (lo + hi) // 2
        if row[m] < draw:
            lo = m + 1
        else:
            hi = m
    return lo


def int_block_set(row, K, seed):
    s = (seed & 0xFFFFFFFF) or 0x9E3779B9
    s ^= (s << 13) & 0xFFFFFFFF
    s ^= s >> 17
    s ^= (s << 5) & 0xFFFFFFFF
    d = min(K, int_degree(row, K, s))
    picked = set()
    while len(picked) < d:
        s ^= (s << 13) & 0xFFFFFFFF
        s ^= s >> 17
        s ^= (s << 5) & 0xFFFFFFFF
        picked.add((s * K) >> 32)
    return frozenset(picked)


def verify(K):
    row = cdf_int(K)
    fcdf = tx.soliton_cdf(K)
    bad = 0
    for seed in range(0, 65536):
        want = frozenset(tx.block_indices(seed, K, fcdf))
        got = int_block_set(row, K, seed)
        if want != got:
            bad += 1
            if bad <= 3:
                sys.stderr.write("  K=%d seed=%d: float=%s int=%s\n"
                                 % (K, seed, sorted(want), sorted(got)))
    return bad


def emit(kmin, kmax):
    rows = []
    for K in range(kmin, kmax + 1):
        r = cdf_int(K)
        vals = ", ".join("0x%08x" % v for v in r) + ("," if K < kmax else "")
        rows.append("    { %s }," % vals if K < kmax else "    { %s }" % vals)
    body = "\n".join(rows)
    return f"""\
/* soliton_table.h - generated by tools/soliton_table.py; do not edit.
 *
 * Fixed-point robust-soliton CDF for the device-side fountain encoder
 * (spec/PROFILE-A.md section 5). Row K-{kmin} holds entries [1..K];
 * entry m = round(cdf(m) * 2^32), clamped. Verified: all 65536 seeds match
 * the floating-point decoder for every K in this range.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef EARSHOT_SOLITON_TABLE_H
#define EARSHOT_SOLITON_TABLE_H

#include <stdint.h>

#define ESH_SOLITON_KMIN {kmin}
#define ESH_SOLITON_KMAX {kmax}

static const uint32_t esh_soliton_cdf[ESH_SOLITON_KMAX - ESH_SOLITON_KMIN + 1]
                                     [ESH_SOLITON_KMAX + 1] = {{
{body}
}};

#endif /* EARSHOT_SOLITON_TABLE_H */
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--kmin", type=int, default=1)
    ap.add_argument("--kmax", type=int, default=32)
    ap.add_argument("--check-only", action="store_true")
    args = ap.parse_args()

    total_bad = 0
    for K in range(max(1, args.kmin), args.kmax + 1):
        bad = verify(K)
        total_bad += bad
        print("K=%2d  %s" % (K, "ok" if bad == 0 else "MISMATCH x%d" % bad))
    if total_bad:
        sys.exit("verification failed: %d mismatching seeds" % total_bad)

    if args.check_only:
        print("all K verified, table not written")
        return

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(emit(args.kmin, args.kmax))
    print("wrote", os.path.relpath(OUT, os.path.dirname(OUT) + "/../.."))


if __name__ == "__main__":
    main()
